# Configuraci贸n para Render
# Este archivo le dice a Render c贸mo ejecutar tu aplicaci贸n

# Comando para iniciar la aplicaci贸n
web: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120

# Variables de entorno por defecto
ADMIN_PASSWORD=changeme123
AKASHIA_CSV_PATH=/opt/render/project/src/submissions.csv
